language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install coveralls
  - pip install tox
install: 
  - pip install .
script: tox
after_success:
  - pytest --cov-report term --cov=deflatebr
  - coveralls