language: python
python:
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install coveralls
  - pip install tox
install: 
  - pip install .
script: coverage run -m pytest
after_success:
  - coverage report -m
  - coveralls